/*******************************************************************************
 * Copyright (c) 2016 Matt Day, Cisco and others
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal 
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *******************************************************************************/
package com.cisco.matday.ucsd.hp3par.reports.tabular;

import com.cisco.matday.ucsd.hp3par.constants.HP3ParConstants;
import com.cisco.matday.ucsd.hp3par.reports.actions.CreateVolumeAction;
import com.cisco.matday.ucsd.hp3par.reports.actions.CreateVolumeCopyAction;
import com.cisco.matday.ucsd.hp3par.reports.actions.CreateVolumeSnapshotAction;
import com.cisco.matday.ucsd.hp3par.reports.actions.DeleteVolumeAction;
import com.cisco.matday.ucsd.hp3par.reports.actions.VolumeDoubleClickActionReport;
import com.cloupia.model.cIM.DynReportContext;
import com.cloupia.model.cIM.ReportContextRegistry;
import com.cloupia.service.cIM.inframgr.reportengine.ContextMapRule;
import com.cloupia.service.cIM.inframgr.reports.simplified.CloupiaReportAction;
import com.cloupia.service.cIM.inframgr.reports.simplified.CloupiaReportWithActions;

/**
 * Tabular list of volumes with action buttons
 * 
 * @author Matt Day
 *
 */
public class VolumeReport extends CloupiaReportWithActions {
	/**
	 * Unique identifier for this report
	 */
	public final static String REPORT_NAME = "com.cisco.matday.ucsd.hp3par.reports.VolumeReport";
	private final static String REPORT_LABEL = "Volumes";

	/**
	 * Overridden default constructor which sets the management column (0)
	 */
	public VolumeReport() {
		super();
		// IMPORTANT: this tells the framework which column of this report you
		// want to pass as the report context id
		// when there is a UI action being launched in this report
		this.setMgmtColumnIndex(0);
	}

	@Override
	public Class<VolumeReportImpl> getImplementationClass() {
		return VolumeReportImpl.class;
	}

	@Override
	public CloupiaReportAction[] getActions() {
		CloupiaReportAction[] actions = {
				new VolumeDoubleClickActionReport(), new CreateVolumeAction(), new DeleteVolumeAction(),
				new CreateVolumeSnapshotAction(), new CreateVolumeCopyAction(),
		};
		return actions;
	}

	@Override
	public String getReportLabel() {
		return VolumeReport.REPORT_LABEL;
	}

	@Override
	public String getReportName() {
		return VolumeReport.REPORT_NAME;
	}

	@Override
	public boolean isEasyReport() {
		return false;
	}

	@Override
	public boolean isLeafReport() {
		return false;
	}

	public int getMenuID() {
		return 51;
	}

	@Override
	public ContextMapRule[] getMapRules() {
		// i'm using an autogenerated report context (which I registered in
		// NimbleModule), as mentioned in documentation
		// the type may vary depending on deployments, so the safest way to
		// retrieve the auto generated type value
		// is to use the getContextByName api!
		DynReportContext context = ReportContextRegistry.getInstance()
				.getContextByName(HP3ParConstants.INFRA_ACCOUNT_TYPE);
		ContextMapRule rule = new ContextMapRule();
		rule.setContextName(context.getId());
		rule.setContextType(context.getType());

		ContextMapRule[] rules = new ContextMapRule[1];
		rules[0] = rule;

		return rules;
	}

}
